// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error)
	AddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*AddPlayerResponse, error)
	GetNextPlayer(ctx context.Context, in *GetNextPlayerRequest, opts ...grpc.CallOption) (*GetNextPlayerResponse, error)
	Roll(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error)
	GetGameEvents(ctx context.Context, in *GetGameEventsRequest, opts ...grpc.CallOption) (GameService_GetGameEventsClient, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*StartGameResponse, error) {
	out := new(StartGameResponse)
	err := c.cc.Invoke(ctx, "/api.GameService/StartGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) AddPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*AddPlayerResponse, error) {
	out := new(AddPlayerResponse)
	err := c.cc.Invoke(ctx, "/api.GameService/AddPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetNextPlayer(ctx context.Context, in *GetNextPlayerRequest, opts ...grpc.CallOption) (*GetNextPlayerResponse, error) {
	out := new(GetNextPlayerResponse)
	err := c.cc.Invoke(ctx, "/api.GameService/GetNextPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) Roll(ctx context.Context, in *RollRequest, opts ...grpc.CallOption) (*RollResponse, error) {
	out := new(RollResponse)
	err := c.cc.Invoke(ctx, "/api.GameService/Roll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGameEvents(ctx context.Context, in *GetGameEventsRequest, opts ...grpc.CallOption) (GameService_GetGameEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GameService_serviceDesc.Streams[0], "/api.GameService/GetGameEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceGetGameEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GameService_GetGameEventsClient interface {
	Recv() (*GetGameEventsResponse, error)
	grpc.ClientStream
}

type gameServiceGetGameEventsClient struct {
	grpc.ClientStream
}

func (x *gameServiceGetGameEventsClient) Recv() (*GetGameEventsResponse, error) {
	m := new(GetGameEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error)
	AddPlayer(context.Context, *AddPlayerRequest) (*AddPlayerResponse, error)
	GetNextPlayer(context.Context, *GetNextPlayerRequest) (*GetNextPlayerResponse, error)
	Roll(context.Context, *RollRequest) (*RollResponse, error)
	GetGameEvents(*GetGameEventsRequest, GameService_GetGameEventsServer) error
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) StartGame(context.Context, *StartGameRequest) (*StartGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (*UnimplementedGameServiceServer) AddPlayer(context.Context, *AddPlayerRequest) (*AddPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlayer not implemented")
}
func (*UnimplementedGameServiceServer) GetNextPlayer(context.Context, *GetNextPlayerRequest) (*GetNextPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextPlayer not implemented")
}
func (*UnimplementedGameServiceServer) Roll(context.Context, *RollRequest) (*RollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Roll not implemented")
}
func (*UnimplementedGameServiceServer) GetGameEvents(*GetGameEventsRequest, GameService_GetGameEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetGameEvents not implemented")
}
func (*UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameService/StartGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_AddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).AddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameService/AddPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).AddPlayer(ctx, req.(*AddPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetNextPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetNextPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameService/GetNextPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetNextPlayer(ctx, req.(*GetNextPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_Roll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Roll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameService/Roll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Roll(ctx, req.(*RollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGameEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetGameEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServiceServer).GetGameEvents(m, &gameServiceGetGameEventsServer{stream})
}

type GameService_GetGameEventsServer interface {
	Send(*GetGameEventsResponse) error
	grpc.ServerStream
}

type gameServiceGetGameEventsServer struct {
	grpc.ServerStream
}

func (x *gameServiceGetGameEventsServer) Send(m *GetGameEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _GameService_StartGame_Handler,
		},
		{
			MethodName: "AddPlayer",
			Handler:    _GameService_AddPlayer_Handler,
		},
		{
			MethodName: "GetNextPlayer",
			Handler:    _GameService_GetNextPlayer_Handler,
		},
		{
			MethodName: "Roll",
			Handler:    _GameService_Roll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetGameEvents",
			Handler:       _GameService_GetGameEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/game/api/deathroll.proto",
}
